#ifndef CONFIG_H
#define CONFIG_H

#define TILE_SIZE 32
#define MAP_WIDTH_IN_TILES 25
#define MAP_HEIGHT_IN_TILES 19

#define SCREEN_WIDTH (MAP_WIDTH_IN_TILES * TILE_SIZE)
#define SCREEN_HEIGHT (MAP_HEIGHT_IN_TILES * TILE_SIZE)

#endif // CONFIG_H
